### ISSUE TITLE
Failed to add "Ok", "Cancel" button at Juice Dialog 

### ISSUE THREAD

**Issue by khorshed** [appendto/juiceui#8] opened 2012-03-06 03:37 UTC
I have tried to to put a Ok button on Juice Dialog  using the code below
 <div class="empbase">

```
            <div id="_Default" class="basic-dialog" title="Basic dialog" runat="server">
                <p>
                    This is the default dialog which is useful for displaying information. The dialog
                    window can be moved, resized and closed with the 'x' icon.</p>
            </div>
            <juice:Dialog TargetControlID="_Default" AutoOpen="false" runat="server" Buttons="Ok" />
            <p>
                <button id="_DefaultButton" class="open-dialog" runat="server">
                    Open Dialog</button>
                <juice:Button TargetControlID="_DefaultButton" runat="server" />
            </p>
        </div>
```

I also used the different format like  <juice:Dialog TargetControlID="_Default" AutoOpen="false" runat="server" Buttons=" 'OK' " /> etc. But failed. It works fine when I used  the following Jquery script

$(document).ready(function () {
    // Respond to the click
    $(".open-dialog").click(function (e) {
        e.preventDefault();
        // Open the dialog
        $(".basic-dialog").dialog({
           buttons: { "Ok": function () { $(this).dialog("close"); } }
        });

```
});
```

});

please help me how can I use Dialog properly.

**Comment by shellscape** [comment] 2012-03-06 15:08
Duplicate of #7. Closing.

This was a bug, but has been fixed. If you're looking for further support, please use one of the community support vectors listed on juiceui.com.

**Closed as completed by shellscape** 2012-03-06 15:08 UTC
